# Generated by Django 3.1.3 on 2020-12-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('region', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=12)),
                ('year', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('bucket', models.CharField(max_length=5)),
            ],
        ),
    ]
